service:
  name: product-catalog-service
# app and org for use with dashboard.serverless.com
# app: product-catalog-service
# org: montera-82-org


# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    PRODUCTS_TABLE_NAME: ${self:custom.ProductsTable.name}
  iamRoleStatements:
    - ${file(iam/ProductsTableIAM.yml):ProductsTableIAM}
resources:
  Resources:
    ProductsTable: ${file(resources/ProductsTable.yml):ProductsTable}  

functions:
  createProduct:
    handler: src/handler.create
    events:
      - http:
          method: POST
          path: products

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  ProductsTable:
    name: !Ref ProductsTable
    arn: !GetAtt ProductsTable.Arn  